# ============================================================
# [SECTION 1] Modal + Anthropic imports and app initialization
# ============================================================

import os
import re
import modal
import anthropic

app = modal.App("querymind-ai")


# ============================================================
# [SECTION 2] SCHEMA CONTEXT
# ============================================================

SCHEMA_CONTEXT = {
    "merchants": {
        "description": "Stores merchant profile and business information",
        "columns": {
            "id":         {"type": "INT",       "description": "Primary key, unique merchant identifier"},
            "name":       {"type": "VARCHAR",   "description": "Merchant display name"},
            "category":   {"type": "VARCHAR",   "description": "Business category (e.g., F&B, Retail, Services)"},
            "amount":     {"type": "DECIMAL",   "description": "Aggregated transaction volume for this merchant"},
            "created_at": {"type": "TIMESTAMP", "description": "Account creation timestamp"},
        },
        "sample_values": {
            "category": ["F&B", "Retail", "Services", "E-commerce"],
        }
    },
    "transactions": {
        "description": "Records every payment transaction processed through the platform",
        "columns": {
            "id":          {"type": "INT",       "description": "Primary key, unique transaction identifier"},
            "merchant_id": {"type": "INT",       "description": "Foreign key referencing merchants.id"},
            "name":        {"type": "VARCHAR",   "description": "Transaction reference name or label"},
            "amount":      {"type": "DECIMAL",   "description": "Transaction amount in local currency (VND)"},
            "status":      {"type": "VARCHAR",   "description": "Transaction status: completed | pending | failed"},
            "created_at":  {"type": "TIMESTAMP", "description": "Transaction timestamp in UTC"},
        },
        "sample_values": {
            "status": ["completed", "pending", "failed"],
        },
        "relationships": {
            "merchant_id": "REFERENCES merchants(id)"
        }
    }
}


def format_schema(schema: dict) -> str:
    lines = []
    for table, meta in schema.items():
        lines.append(f"TABLE: {table}")
        lines.append(f"  Description: {meta['description']}")
        for col, info in meta["columns"].items():
            lines.append(f"  - {col} ({info['type']}): {info['description']}")
        if "relationships" in meta:
            for col, ref in meta["relationships"].items():
                lines.append(f"  - {col} {ref}")
        lines.append("")
    return "\n".join(lines)


# ============================================================
# [SECTION 3] SYSTEM PROMPTS
# ============================================================

TRANSLATE_SYSTEM_PROMPT = f"""You are QueryMind AI, an expert SQL engineer embedded inside an analytics platform.
Your job is to translate Vietnamese business questions into production-ready SQL queries.

DATABASE SCHEMA:
You are working with a PostgreSQL database containing these tables:
{format_schema(SCHEMA_CONTEXT)}

RULES — FOLLOW STRICTLY:
1. Output ONLY a single SQL code block. Format: ```sql\\n<query>\\n```
2. Do NOT output any explanation, preamble, or commentary outside the code block.
3. Do NOT output markdown prose. Only the code block.
4. Use proper SQL formatting: each clause on a new line, uppercase keywords.
5. Prefer DATE_TRUNC for time-based grouping. Use 'month' granularity by default.
6. Always use explicit JOIN conditions, never implicit comma joins.
7. Add a single-line SQL comment at the top of the query: -- Generated by QueryMind AI
8. If the question is ambiguous, make the most reasonable business assumption and proceed.
9. Filter transactions to status = 'completed' unless the user asks otherwise.
10. Always alias aggregation columns descriptively (e.g., SUM(t.amount) AS total_revenue).
"""

EXPLAIN_SYSTEM_PROMPT = f"""You are QueryMind AI, a friendly and precise SQL instructor.
Your job is to explain SQL queries to non-technical Vietnamese Data Analysts.

DATABASE SCHEMA:
{format_schema(SCHEMA_CONTEXT)}

RULES — FOLLOW STRICTLY:
1. Structure your explanation into EXACTLY 4 steps.
2. Format MUST be:
   STEP 1: [Title in Vietnamese]
   [2-3 sentence explanation in Vietnamese, plain language, no jargon]

   STEP 2: [Title in Vietnamese]
   [explanation]

   STEP 3: [Title in Vietnamese]
   [explanation]

   STEP 4: [Title in Vietnamese]
   [explanation]

3. Use the format above verbatim. The frontend will parse "STEP N:" as a delimiter.
4. Reference actual column names from the schema where relevant.
5. Do NOT add any text before STEP 1 or after STEP 4.
6. Use simple, encouraging Vietnamese. Avoid "complex", "advanced", or intimidating language.
"""


# ============================================================
# [SECTION 4] BACKEND LOGIC
# ============================================================

def call_claude(system_prompt: str, user_message: str) -> str:
    client = anthropic.Anthropic()
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2048,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}]
    )
    return message.content[0].text


def parse_sql_from_response(raw: str) -> str:
    match = re.search(r"```sql\s*([\s\S]*?)\s*```", raw)
    return match.group(1).strip() if match else raw.strip()


def parse_steps_from_response(raw: str) -> list[dict]:
    steps = []
    pattern = r"STEP (\d+):\s*(.+?)\n([\s\S]*?)(?=STEP \d+:|$)"
    for match in re.finditer(pattern, raw.strip(), re.MULTILINE):
        steps.append({
            "number": int(match.group(1)),
            "title":  match.group(2).strip(),
            "body":   match.group(3).strip()
        })
    return steps


# ============================================================
# [SECTION 5] API ENDPOINTS — Modal @app.function web endpoints
# ============================================================
# HTML_LANDING and HTML_WORKSPACE are module-level string constants.
# They are resolved at call time (not definition time), so SECTION 6 & 7
# reassignments will be in effect before any request is ever served.

# ============================================================
# [SECTION 6] HTML_LANDING — Landing Page
# ============================================================
HTML_LANDING = """<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>QueryMind AI — AI-Powered SQL Copilot for Analysts</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Geist+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }

    :root {
      --bg-base:            #0B1020;
      --bg-surface:         #0e1323;
      --bg-surface-low:     #161b2b;
      --bg-surface-mid:     #1a1f30;
      --bg-surface-high:    #25293a;
      --text-primary:       #dee1f9;
      --text-secondary:     #bbc9cd;
      --cyan-primary:       #8aebff;
      --cyan-mid:           #22d3ee;
      --cyan-bright:        #2fd9f4;
      --violet-primary:     #d0bcff;
      --violet-deep:        #8b5cf6;
      --violet-darker:      #571bc1;
      --blue-mid:           #adc6ff;
      --success-green:      #4ade80;
      --border-subtle:      rgba(255,255,255,0.08);
      --border-elevated:    rgba(255,255,255,0.15);
      --gradient-cta:       linear-gradient(135deg, #22d3ee 0%, #8b5cf6 100%);
      --radius-sm:          4px;
      --radius-md:          12px;
      --radius-lg:          16px;
      --radius-xl:          24px;
      --radius-full:        9999px;
    }

    html { scroll-behavior: smooth; }

    body {
      font-family: 'Inter', -apple-system, sans-serif;
      background-color: var(--bg-base);
      color: var(--text-primary);
      line-height: 1.5;
      overflow-x: hidden;
    }

    body::before {
      content: '';
      position: fixed;
      inset: 0;
      background:
        radial-gradient(ellipse 65% 55% at 72% 38%, rgba(34,211,238,0.08) 0%, transparent 70%),
        radial-gradient(ellipse 55% 65% at 28% 65%, rgba(139,92,246,0.07) 0%, transparent 70%),
        radial-gradient(ellipse 40% 40% at 50% 10%, rgba(87,27,193,0.04) 0%, transparent 70%);
      pointer-events: none;
      z-index: 0;
    }

    /* ===========================
       NAVIGATION
    =========================== */
    nav {
      position: sticky;
      top: 0;
      z-index: 100;
      height: 64px;
      background: rgba(11,16,32,0.85);
      backdrop-filter: blur(20px);
      -webkit-backdrop-filter: blur(20px);
      border-bottom: 1px solid rgba(255,255,255,0.07);
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 64px;
    }

    .nav-logo {
      display: flex;
      align-items: center;
      gap: 10px;
      text-decoration: none;
      flex-shrink: 0;
    }

    .nav-logo-icon {
      width: 32px;
      height: 32px;
      flex-shrink: 0;
    }

    .nav-logo-text {
      font-size: 17px;
      font-weight: 700;
      color: var(--text-primary);
      letter-spacing: -0.02em;
    }

    .nav-links {
      display: flex;
      align-items: center;
      gap: 36px;
      list-style: none;
    }

    .nav-links a {
      font-size: 14px;
      font-weight: 500;
      color: var(--text-secondary);
      text-decoration: none;
      transition: color 0.2s;
    }
    .nav-links a:hover { color: var(--text-primary); }

    .nav-actions { display: flex; align-items: center; gap: 10px; }

    .btn-ghost {
      font-size: 14px; font-weight: 500;
      color: var(--text-secondary);
      background: none; border: none;
      cursor: pointer; padding: 8px 16px;
      border-radius: var(--radius-lg);
      transition: color 0.2s, background 0.2s;
    }
    .btn-ghost:hover { color: var(--text-primary); background: rgba(255,255,255,0.05); }

    .btn-nav-cta {
      font-size: 14px; font-weight: 600; color: #000;
      background: var(--gradient-cta);
      border: none; border-radius: var(--radius-full);
      padding: 9px 20px; cursor: pointer;
      transition: transform 0.2s, box-shadow 0.2s;
      text-decoration: none; display: inline-block;
    }
    .btn-nav-cta:hover { transform: translateY(-1px); box-shadow: 0 6px 20px rgba(34,211,238,0.35); }

    /* ===========================
       HERO SECTION
    =========================== */
    .hero {
      position: relative; z-index: 1;
      min-height: calc(100vh - 64px);
      display: flex; align-items: center;
      padding: 80px 64px;
      gap: 48px;
      max-width: 1440px;
      margin: 0 auto;
    }

    .hero-left { flex: 0 0 52%; max-width: 580px; }

    .hero-badge {
      display: inline-flex; align-items: center; gap: 8px;
      padding: 6px 14px;
      background: rgba(34,211,238,0.08);
      border: 1px solid rgba(34,211,238,0.28);
      border-radius: var(--radius-full);
      margin-bottom: 28px;
    }

    .hero-badge-dot {
      width: 6px; height: 6px;
      border-radius: 50%; background: var(--cyan-mid);
      animation: pulse-dot 2s infinite;
    }
    @keyframes pulse-dot {
      0%, 100% { opacity: 1; box-shadow: 0 0 0 0 rgba(34,211,238,0.5); }
      50% { opacity: 0.6; box-shadow: 0 0 0 4px rgba(34,211,238,0); }
    }

    .hero-badge span {
      font-family: 'Geist Mono', monospace;
      font-size: 11px; font-weight: 600;
      color: var(--cyan-mid);
      letter-spacing: 0.1em; text-transform: uppercase;
    }

    .hero h1 {
      font-size: 54px; font-weight: 800;
      line-height: 1.07; letter-spacing: -0.028em;
      color: var(--text-primary); margin-bottom: 22px;
    }

    .h1-gradient {
      background: linear-gradient(135deg, #22d3ee 0%, #a78bfa 60%, #d0bcff 100%);
      -webkit-background-clip: text; -webkit-text-fill-color: transparent;
      background-clip: text;
    }

    .hero-sub {
      font-size: 18px; font-weight: 400;
      color: var(--text-secondary); line-height: 1.68;
      max-width: 480px; margin-bottom: 36px;
    }

    .hero-cta-row {
      display: flex; align-items: center;
      gap: 14px; flex-wrap: wrap; margin-bottom: 36px;
    }

    .btn-primary {
      display: inline-flex; align-items: center; gap: 8px;
      font-size: 16px; font-weight: 600; color: #020617;
      background: var(--gradient-cta);
      border: none; border-radius: var(--radius-lg);
      padding: 14px 28px; cursor: pointer;
      text-decoration: none;
      transition: transform 0.2s ease, box-shadow 0.2s ease;
      white-space: nowrap;
    }
    .btn-primary:hover {
      transform: translateY(-2px);
      box-shadow: 0 10px 36px rgba(34,211,238,0.38);
    }

    .btn-secondary {
      display: inline-flex; align-items: center; gap: 8px;
      font-size: 15px; font-weight: 500; color: var(--text-primary);
      background: rgba(255,255,255,0.05);
      border: 1px solid rgba(255,255,255,0.15);
      border-radius: var(--radius-lg);
      padding: 14px 24px; cursor: pointer;
      text-decoration: none;
      transition: background 0.2s, border-color 0.2s;
      white-space: nowrap;
    }
    .btn-secondary:hover {
      background: rgba(255,255,255,0.09); border-color: rgba(255,255,255,0.28);
    }

    .hero-trust { display: flex; align-items: center; gap: 14px; }

    .hero-avatars { display: flex; }

    .hero-avatar {
      width: 30px; height: 30px;
      border-radius: 50%;
      border: 2px solid var(--bg-base);
      margin-left: -7px;
      display: flex; align-items: center; justify-content: center;
      font-size: 11px; font-weight: 700; color: #000;
    }
    .hero-avatars .hero-avatar:first-child { margin-left: 0; }

    .hero-trust-text {
      font-size: 13px; color: rgba(187,201,205,0.65);
    }

    /* ===========================
       HERO GRAPHIC (3D Recreation)
    =========================== */
    .hero-right {
      flex: 1; position: relative;
      height: 500px;
      display: flex; align-items: center; justify-content: center;
    }

    .hero-graphic { position: relative; width: 100%; height: 100%; }

    .hero-glow {
      position: absolute;
      width: 420px; height: 300px; border-radius: 50%;
      background: radial-gradient(ellipse, rgba(34,211,238,0.18) 0%, rgba(139,92,246,0.12) 45%, transparent 72%);
      top: 50%; left: 50%;
      transform: translate(-50%, -50%);
      filter: blur(50px);
      animation: glow-breathe 4s ease-in-out infinite;
    }
    @keyframes glow-breathe {
      0%, 100% { transform: translate(-50%, -50%) scale(1); opacity: 0.75; }
      50% { transform: translate(-50%, -50%) scale(1.18); opacity: 1; }
    }

    /* NLP input pill */
    .nlp-pill {
      position: absolute;
      left: -8px; top: 50%;
      transform: translateY(-50%);
      background: rgba(22,27,43,0.9);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(34,211,238,0.45);
      border-radius: var(--radius-full);
      padding: 14px 22px;
      width: 192px;
      box-shadow: 0 0 40px rgba(34,211,238,0.22), 0 0 0 1px rgba(34,211,238,0.1) inset;
      animation: float-pill 3.5s ease-in-out infinite;
      z-index: 10;
    }
    @keyframes float-pill {
      0%, 100% { transform: translateY(-50%) translateX(0px); }
      50% { transform: translateY(-50%) translateX(-8px); }
    }

    .nlp-pill-label {
      font-family: 'Geist Mono', monospace;
      font-size: 10px; font-weight: 600;
      color: var(--cyan-mid); letter-spacing: 0.1em;
      text-transform: uppercase; margin-bottom: 5px;
    }

    .nlp-pill-text {
      font-size: 13px; font-weight: 500;
      color: var(--text-primary); line-height: 1.45;
    }

    /* SVG flow */
    .flow-svg {
      position: absolute; top: 0; left: 0;
      width: 100%; height: 100%;
      pointer-events: none;
    }

    /* Floating SQL cards */
    .sql-float-card {
      position: absolute;
      background: rgba(10,14,28,0.88);
      backdrop-filter: blur(16px);
      border: 1px solid rgba(255,255,255,0.11);
      border-top: 1px solid rgba(255,255,255,0.18);
      border-radius: var(--radius-md);
      padding: 14px 16px;
      z-index: 10;
    }

    .sql-float-card.c1 {
      top: 8%; right: 4%;  width: 208px;
      animation: fc1 4.2s ease-in-out infinite;
      box-shadow: 0 12px 40px rgba(0,0,0,0.5), 0 0 20px rgba(34,211,238,0.08);
    }
    .sql-float-card.c2 {
      top: 40%; right: 0%; width: 200px;
      animation: fc2 3.8s ease-in-out infinite 0.6s;
      box-shadow: 0 12px 40px rgba(0,0,0,0.5), 0 0 20px rgba(139,92,246,0.08);
    }
    .sql-float-card.c3 {
      top: 70%; right: 6%; width: 188px;
      animation: fc3 4.5s ease-in-out infinite 0.3s;
      box-shadow: 0 12px 40px rgba(0,0,0,0.5), 0 0 20px rgba(34,211,238,0.06);
    }

    @keyframes fc1 {
      0%, 100% { transform: translateY(0px) rotate(0.3deg); }
      50% { transform: translateY(-12px) rotate(-0.3deg); }
    }
    @keyframes fc2 {
      0%, 100% { transform: translateY(0px) rotate(-0.2deg); }
      50% { transform: translateY(10px) rotate(0.2deg); }
    }
    @keyframes fc3 {
      0%, 100% { transform: translateY(0px) rotate(0.2deg); }
      50% { transform: translateY(-8px) rotate(-0.2deg); }
    }

    .card-dots { display: flex; gap: 5px; margin-bottom: 10px; }
    .cd { width: 8px; height: 8px; border-radius: 50%; }
    .cd.r { background: #ff5f57; }
    .cd.y { background: #ffbd2e; }
    .cd.g { background: #28c840; }

    .sc { font-family: 'Geist Mono', monospace; font-size: 11.5px; line-height: 1.8; white-space: nowrap; display: block; }
    .kw { color: #c4abff; }
    .fn { color: #22d3ee; }
    .st { color: #86efac; }
    .cl { color: #dee1f9; }
    .nm { color: #fca5a5; }
    .cm { color: #4a5568; font-style: italic; }

    /* ===========================
       FEATURES SECTION
    =========================== */
    .features {
      position: relative; z-index: 1;
      padding: 100px 64px;
      max-width: 1440px; margin: 0 auto;
    }

    .section-header { text-align: center; margin-bottom: 56px; }

    .section-label {
      font-family: 'Geist Mono', monospace;
      font-size: 11px; font-weight: 600;
      color: var(--cyan-mid); letter-spacing: 0.14em;
      text-transform: uppercase; margin-bottom: 12px;
    }

    .section-title {
      font-size: 36px; font-weight: 700;
      color: var(--text-primary);
      letter-spacing: -0.022em; margin-bottom: 14px;
    }

    .section-sub {
      font-size: 17px; color: var(--text-secondary);
      max-width: 500px; margin: 0 auto; line-height: 1.65;
    }

    .features-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 24px;
    }

    .feat-card {
      background: rgba(255,255,255,0.03);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border: 1px solid rgba(255,255,255,0.08);
      border-top: 1px solid rgba(255,255,255,0.13);
      border-radius: var(--radius-xl);
      padding: 32px;
      transition: border-color 0.3s, transform 0.3s, box-shadow 0.3s;
      cursor: default;
    }
    .feat-card:hover {
      border-color: rgba(34,211,238,0.22);
      transform: translateY(-5px);
      box-shadow: 0 20px 50px rgba(0,0,0,0.35);
    }

    .feat-icon {
      width: 50px; height: 50px; border-radius: 14px;
      display: flex; align-items: center; justify-content: center;
      font-size: 22px; margin-bottom: 22px;
    }
    .feat-icon.c { background: rgba(34,211,238,0.1); border: 1px solid rgba(34,211,238,0.22); }
    .feat-icon.v { background: rgba(139,92,246,0.1); border: 1px solid rgba(139,92,246,0.22); }
    .feat-icon.b { background: rgba(173,198,255,0.1); border: 1px solid rgba(173,198,255,0.22); }

    .feat-card h3 {
      font-size: 20px; font-weight: 600;
      color: var(--text-primary); margin-bottom: 12px;
    }

    .feat-card p {
      font-size: 15px; color: var(--text-secondary);
      line-height: 1.68; margin-bottom: 22px;
    }

    .feat-tag {
      display: inline-flex; align-items: center; gap: 6px;
      font-family: 'Geist Mono', monospace;
      font-size: 11px; font-weight: 600;
      letter-spacing: 0.06em; text-transform: uppercase;
      padding: 5px 12px; border-radius: var(--radius-full);
    }
    .feat-tag.c { background: rgba(34,211,238,0.08); color: var(--cyan-mid); border: 1px solid rgba(34,211,238,0.2); }
    .feat-tag.v { background: rgba(139,92,246,0.08); color: var(--violet-primary); border: 1px solid rgba(139,92,246,0.2); }
    .feat-tag.b { background: rgba(173,198,255,0.08); color: var(--blue-mid); border: 1px solid rgba(173,198,255,0.2); }

    /* ===========================
       SOCIAL PROOF
    =========================== */
    .social-proof {
      position: relative; z-index: 1;
      padding: 40px 64px 60px;
      max-width: 1440px; margin: 0 auto;
      text-align: center;
    }

    .sp-label {
      font-family: 'Geist Mono', monospace;
      font-size: 11px; color: rgba(187,201,205,0.4);
      letter-spacing: 0.1em; text-transform: uppercase;
      margin-bottom: 28px;
    }

    .logo-strip {
      display: flex; align-items: center;
      justify-content: center; gap: 52px; flex-wrap: wrap;
    }

    .logo-item {
      font-size: 17px; font-weight: 700;
      color: rgba(222,225,249,0.2);
      letter-spacing: -0.01em;
      transition: color 0.25s;
    }
    .logo-item:hover { color: rgba(222,225,249,0.45); }

    /* ===========================
       CTA BANNER
    =========================== */
    .cta-banner {
      position: relative; z-index: 1;
      padding: 40px 64px 100px;
      max-width: 1440px; margin: 0 auto;
    }

    .cta-inner {
      background: rgba(255,255,255,0.028);
      backdrop-filter: blur(16px);
      border: 1px solid rgba(255,255,255,0.08);
      border-top: 1px solid rgba(255,255,255,0.16);
      border-radius: var(--radius-xl);
      padding: 72px 48px;
      text-align: center;
      position: relative; overflow: hidden;
    }

    .cta-glow {
      position: absolute;
      top: -80px; left: 50%;
      transform: translateX(-50%);
      width: 500px; height: 240px;
      background: radial-gradient(ellipse, rgba(34,211,238,0.1) 0%, transparent 70%);
      pointer-events: none;
    }

    .cta-inner h2 {
      font-size: 42px; font-weight: 700;
      color: var(--text-primary);
      letter-spacing: -0.022em; margin-bottom: 14px;
      position: relative; z-index: 1;
    }

    .cta-inner p {
      font-size: 18px; color: var(--text-secondary);
      margin-bottom: 38px; position: relative; z-index: 1;
    }

    .cta-btns {
      display: flex; align-items: center;
      justify-content: center; gap: 16px;
      position: relative; z-index: 1;
    }

    /* ===========================
       FOOTER
    =========================== */
    footer {
      position: relative; z-index: 1;
      background: rgba(255,255,255,0.018);
      border-top: 1px solid rgba(255,255,255,0.06);
      padding: 32px 64px;
    }

    .footer-inner {
      max-width: 1440px; margin: 0 auto;
      display: flex; align-items: center;
      justify-content: space-between; flex-wrap: wrap; gap: 16px;
    }

    .footer-left {
      display: flex; align-items: center;
      gap: 10px; font-size: 13px;
      color: rgba(187,201,205,0.4);
    }

    .footer-logo-text { font-weight: 700; color: rgba(222,225,249,0.5); font-size: 14px; }

    .footer-links { display: flex; gap: 24px; }
    .footer-links a {
      font-size: 13px; color: rgba(187,201,205,0.35);
      text-decoration: none; transition: color 0.2s;
    }
    .footer-links a:hover { color: var(--text-secondary); }
  </style>
</head>
<body>

  <!-- ===== NAVIGATION ===== -->
  <nav>
    <a href="/" class="nav-logo">
      <svg class="nav-logo-icon" viewBox="0 0 32 32" fill="none">
        <rect width="32" height="32" rx="8" fill="url(#lg1)"/>
        <path d="M7 17l3.5-5L14 18l3-7 4 9 3.5-5" stroke="white" stroke-width="1.8"
              stroke-linecap="round" stroke-linejoin="round"/>
        <defs>
          <linearGradient id="lg1" x1="0" y1="0" x2="32" y2="32">
            <stop offset="0%" stop-color="#22d3ee"/>
            <stop offset="100%" stop-color="#8b5cf6"/>
          </linearGradient>
        </defs>
      </svg>
      <span class="nav-logo-text">QueryMind AI</span>
    </a>

    <ul class="nav-links">
      <li><a href="#">Docs</a></li>
      <li><a href="#">Features</a></li>
      <li><a href="#">Customers</a></li>
      <li><a href="#">Changelog</a></li>
    </ul>

    <div class="nav-actions">
      <button class="btn-ghost">Sign In</button>
      <a href="/workspace" class="btn-nav-cta">Start Free &#x2192;</a>
    </div>
  </nav>

  <!-- ===== HERO ===== -->
  <section class="hero">
    <div class="hero-left">
      <div class="hero-badge">
        <div class="hero-badge-dot"></div>
        <span>&#x2736; AI POWERED V1.0</span>
      </div>

      <h1>Ask Questions in<br>Vietnamese. Get<br><span class="h1-gradient">Production-Ready SQL</span><br>Instantly.</h1>

      <p class="hero-sub">An AI engine designed for Data Analysts to translate business questions into SQL, explain complex queries, and accelerate analytics workflows.</p>

      <div class="hero-cta-row">
        <a href="/workspace" class="btn-primary">
          Start Querying
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </a>
        <a href="#" class="btn-secondary">
          <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
            <circle cx="7.5" cy="7.5" r="6" stroke="currentColor" stroke-width="1.4"/>
            <path d="M6 5l4 2.5L6 10V5z" fill="currentColor"/>
          </svg>
          See Demo
        </a>
      </div>

      <div class="hero-trust">
        <div class="hero-avatars">
          <div class="hero-avatar" style="background:linear-gradient(135deg,#22d3ee,#0891b2);">N</div>
          <div class="hero-avatar" style="background:linear-gradient(135deg,#8b5cf6,#6d28d9);">T</div>
          <div class="hero-avatar" style="background:linear-gradient(135deg,#86efac,#22c55e);">H</div>
        </div>
        <span class="hero-trust-text">Trusted by 500+ Vietnamese Data Analysts</span>
      </div>
    </div>

    <!-- HERO GRAPHIC — 3D.PNG Recreation -->
    <div class="hero-right">
      <div class="hero-graphic">
        <div class="hero-glow"></div>

        <!-- NLP Input Pill -->
        <div class="nlp-pill">
          <div class="nlp-pill-label">Natural Language</div>
          <div class="nlp-pill-text">Show me sales<br>from last month</div>
        </div>

        <!-- SVG Animated Flow Lines -->
        <svg class="flow-svg" viewBox="0 0 620 500" preserveAspectRatio="xMidYMid meet">
          <defs>
            <linearGradient id="fg1" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%"   stop-color="#22d3ee" stop-opacity="0"/>
              <stop offset="50%"  stop-color="#22d3ee" stop-opacity="0.9"/>
              <stop offset="100%" stop-color="#8b5cf6" stop-opacity="0.6"/>
            </linearGradient>
            <linearGradient id="fg2" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%"   stop-color="#22d3ee" stop-opacity="0"/>
              <stop offset="50%"  stop-color="#2fd9f4" stop-opacity="0.8"/>
              <stop offset="100%" stop-color="#d0bcff" stop-opacity="0.5"/>
            </linearGradient>
            <linearGradient id="fg3" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%"   stop-color="#22d3ee" stop-opacity="0"/>
              <stop offset="50%"  stop-color="#22d3ee" stop-opacity="0.75"/>
              <stop offset="100%" stop-color="#571bc1" stop-opacity="0.4"/>
            </linearGradient>
            <filter id="gf">
              <feGaussianBlur stdDeviation="2.5" result="b"/>
              <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
            </filter>
          </defs>

          <!-- Path 1 &#x2192; top card -->
          <path id="p1" d="M 210 250 C 295 250, 330 140, 400 140" fill="none"/>
          <path d="M 210 250 C 295 250, 330 140, 400 140"
                stroke="url(#fg1)" stroke-width="1.8" fill="none" filter="url(#gf)">
            <animate attributeName="stroke-dasharray" values="0 320;320 0;320 0" keyTimes="0;0.6;1" dur="2.4s" repeatCount="indefinite"/>
            <animate attributeName="opacity" values="0.4;1;0.4" dur="2.4s" repeatCount="indefinite"/>
          </path>
          <path d="M 210 250 C 295 250, 330 140, 400 140"
                stroke="url(#fg1)" stroke-width="5" fill="none" opacity="0.25" filter="url(#gf)">
            <animate attributeName="stroke-dasharray" values="0 320;320 0;320 0" keyTimes="0;0.6;1" dur="2.4s" begin="0.15s" repeatCount="indefinite"/>
          </path>

          <!-- Path 2 &#x2192; middle card -->
          <path id="p2" d="M 210 250 C 300 250, 330 258, 400 258" fill="none"/>
          <path d="M 210 250 C 300 250, 330 258, 400 258"
                stroke="url(#fg2)" stroke-width="2.2" fill="none" filter="url(#gf)">
            <animate attributeName="stroke-dasharray" values="0 260;260 0;260 0" keyTimes="0;0.55;1" dur="2.0s" begin="0.4s" repeatCount="indefinite"/>
            <animate attributeName="opacity" values="0.4;1;0.4" dur="2.0s" begin="0.4s" repeatCount="indefinite"/>
          </path>
          <path d="M 210 250 C 300 250, 330 258, 400 258"
                stroke="url(#fg2)" stroke-width="6" fill="none" opacity="0.2" filter="url(#gf)">
            <animate attributeName="stroke-dasharray" values="0 260;260 0;260 0" keyTimes="0;0.55;1" dur="2.0s" begin="0.55s" repeatCount="indefinite"/>
          </path>

          <!-- Path 3 &#x2192; bottom card -->
          <path id="p3" d="M 210 250 C 295 250, 330 370, 400 375" fill="none"/>
          <path d="M 210 250 C 295 250, 330 370, 400 375"
                stroke="url(#fg3)" stroke-width="1.8" fill="none" filter="url(#gf)">
            <animate attributeName="stroke-dasharray" values="0 300;300 0;300 0" keyTimes="0;0.6;1" dur="2.6s" begin="0.8s" repeatCount="indefinite"/>
            <animate attributeName="opacity" values="0.3;0.9;0.3" dur="2.6s" begin="0.8s" repeatCount="indefinite"/>
          </path>
          <path d="M 210 250 C 295 250, 330 370, 400 375"
                stroke="url(#fg3)" stroke-width="5" fill="none" opacity="0.18" filter="url(#gf)">
            <animate attributeName="stroke-dasharray" values="0 300;300 0;300 0" keyTimes="0;0.6;1" dur="2.6s" begin="0.95s" repeatCount="indefinite"/>
          </path>

          <!-- Traveling particles -->
          <circle r="3.5" fill="#22d3ee" filter="url(#gf)">
            <animateMotion dur="2.4s" repeatCount="indefinite" begin="0.1s"><mpath href="#p1"/></animateMotion>
            <animate attributeName="opacity" values="0;1;1;0" dur="2.4s" repeatCount="indefinite" begin="0.1s"/>
          </circle>
          <circle r="3" fill="#d0bcff" filter="url(#gf)">
            <animateMotion dur="2.0s" repeatCount="indefinite" begin="0.5s"><mpath href="#p2"/></animateMotion>
            <animate attributeName="opacity" values="0;1;1;0" dur="2.0s" repeatCount="indefinite" begin="0.5s"/>
          </circle>
          <circle r="2.5" fill="#22d3ee" filter="url(#gf)">
            <animateMotion dur="2.6s" repeatCount="indefinite" begin="0.9s"><mpath href="#p3"/></animateMotion>
            <animate attributeName="opacity" values="0;0.9;0.9;0" dur="2.6s" repeatCount="indefinite" begin="0.9s"/>
          </circle>

          <!-- Converge point glow -->
          <circle cx="210" cy="250" r="10" fill="rgba(34,211,238,0.15)" filter="url(#gf)">
            <animate attributeName="r" values="8;14;8" dur="2s" repeatCount="indefinite"/>
            <animate attributeName="opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/>
          </circle>
          <circle cx="210" cy="250" r="5" fill="#22d3ee" opacity="0.8"/>
        </svg>

        <!-- Floating SQL Card 1 — Top right -->
        <div class="sql-float-card c1">
          <div class="card-dots"><div class="cd r"></div><div class="cd y"></div><div class="cd g"></div></div>
          <code class="sc"><span class="kw">SELECT</span> <span class="cl">m.name</span><span class="cl">,</span></code>
          <code class="sc">  <span class="fn">SUM</span>(<span class="cl">t.amount</span>)</code>
          <code class="sc">  <span class="kw">AS</span> <span class="cl">total_rev</span></code>
          <code class="sc"><span class="kw">FROM</span> <span class="cl">merchants</span> <span class="cl">m</span></code>
          <code class="sc"><span class="kw">JOIN</span> <span class="cl">transactions t</span></code>
          <code class="sc">  <span class="kw">ON</span> <span class="cl">m.id</span> <span class="kw">=</span> <span class="cl">t.merchant_id</span></code>
        </div>

        <!-- Floating SQL Card 2 — Middle right -->
        <div class="sql-float-card c2">
          <div class="card-dots"><div class="cd r"></div><div class="cd y"></div><div class="cd g"></div></div>
          <code class="sc"><span class="kw">WHERE</span> <span class="cl">t.status</span> <span class="kw">=</span></code>
          <code class="sc">  <span class="st">'completed'</span></code>
          <code class="sc"><span class="kw">GROUP BY</span> <span class="cl">m.name</span></code>
          <code class="sc"><span class="kw">ORDER BY</span></code>
          <code class="sc">  <span class="cl">total_rev</span> <span class="kw">DESC</span></code>
          <code class="sc"><span class="kw">LIMIT</span> <span class="nm">10</span></code>
        </div>

        <!-- Floating SQL Card 3 — Bottom right -->
        <div class="sql-float-card c3">
          <div class="card-dots"><div class="cd r"></div><div class="cd y"></div><div class="cd g"></div></div>
          <code class="sc"><span class="fn">DATE_TRUNC</span>(</code>
          <code class="sc">  <span class="st">'month'</span>,</code>
          <code class="sc">  <span class="cl">t.created_at</span></code>
          <code class="sc">) <span class="kw">AS</span> <span class="cl">month</span></code>
        </div>
      </div>
    </div>
  </section>

  <!-- ===== FEATURES ===== -->
  <section class="features">
    <div class="section-header">
      <div class="section-label">&#x2736; CAPABILITIES</div>
      <h2 class="section-title">Engineered for Technical Depth</h2>
      <p class="section-sub">Three ways QueryMind AI makes every analyst a SQL expert.</p>
    </div>
    <div class="features-grid">
      <div class="feat-card">
        <div class="feat-icon c">
          <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
            <path d="M3 11l4-6 4 8 3-5 4 6" stroke="#22d3ee" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <circle cx="18" cy="4" r="2" fill="#22d3ee" opacity="0.6"/>
            <circle cx="3" cy="18" r="1.5" fill="#22d3ee" opacity="0.4"/>
          </svg>
        </div>
        <h3>Vietnamese &#x2192; SQL</h3>
        <p>Describe your data question naturally in Vietnamese. QueryMind AI translates intent into optimized, production-ready SQL queries instantly.</p>
        <span class="feat-tag c">NLP Translation</span>
      </div>
      <div class="feat-card">
        <div class="feat-icon v">
          <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
            <circle cx="11" cy="8" r="4" stroke="#a78bfa" stroke-width="1.8"/>
            <path d="M7 14c0-2.2 1.8-4 4-4s4 1.8 4 4" stroke="#a78bfa" stroke-width="1.8" stroke-linecap="round"/>
            <path d="M15 6c1.1.7 2 1.9 2 3.5" stroke="#a78bfa" stroke-width="1.4" stroke-linecap="round" opacity="0.5"/>
            <path d="M7 6C5.9 6.7 5 7.9 5 9.5" stroke="#a78bfa" stroke-width="1.4" stroke-linecap="round" opacity="0.5"/>
          </svg>
        </div>
        <h3>Explain Complex Queries</h3>
        <p>Paste any SQL query and receive a plain-language, step-by-step breakdown in Vietnamese. Perfect for learning, auditing, and query review.</p>
        <span class="feat-tag v">Query Intelligence</span>
      </div>
      <div class="feat-card">
        <div class="feat-icon b">
          <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
            <ellipse cx="11" cy="6" rx="7" ry="2.5" stroke="#adc6ff" stroke-width="1.8"/>
            <path d="M4 6v5c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5V6" stroke="#adc6ff" stroke-width="1.8"/>
            <path d="M4 11v5c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-5" stroke="#adc6ff" stroke-width="1.8"/>
          </svg>
        </div>
        <h3>Schema-Aware Generation</h3>
        <p>QueryMind AI knows your table schemas, column types, and relationships — generating queries that join correctly, every time.</p>
        <span class="feat-tag b">Schema Intelligence</span>
      </div>
    </div>
  </section>

  <!-- ===== SOCIAL PROOF ===== -->
  <div class="social-proof">
    <p class="sp-label">Trusted by data teams at leading Vietnamese companies</p>
    <div class="logo-strip">
      <span class="logo-item">VPBank</span>
      <span class="logo-item">Tiki</span>
      <span class="logo-item">MoMo</span>
      <span class="logo-item">Shopee VN</span>
      <span class="logo-item">VNG</span>
      <span class="logo-item">VNPAY</span>
    </div>
  </div>

  <!-- ===== CTA BANNER ===== -->
  <section class="cta-banner">
    <div class="cta-inner">
      <div class="cta-glow"></div>
      <h2>Transform your data workflow today.</h2>
      <p>Join analysts who ship data insights 10&#xD7; faster.</p>
      <div class="cta-btns">
        <a href="/workspace" class="btn-primary">Start Free Trial</a>
        <a href="#" class="btn-secondary">Talk to Sales</a>
      </div>
    </div>
  </section>

  <!-- ===== FOOTER ===== -->
  <footer>
    <div class="footer-inner">
      <div class="footer-left">
        <span class="footer-logo-text">QueryMind AI</span>
        <span>&#xA9; 2025 QueryMind AI. All rights reserved.</span>
      </div>
      <div class="footer-links">
        <a href="#">Privacy Policy</a>
        <a href="#">Terms of Service</a>
        <a href="#">Contact</a>
      </div>
    </div>
  </footer>

</body>
</html>"""

# ============================================================
# [SECTION 7] HTML_WORKSPACE — Workspace Page
# ============================================================
HTML_WORKSPACE = """<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>QueryMind AI &#x2014; Workspace</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Geist+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }

    :root {
      --bg-base:         #0B1020;
      --bg-surface:      #0e1323;
      --bg-surface-low:  #0d1224;
      --bg-surface-mid:  #1a1f30;
      --bg-surface-high: #25293a;
      --text-primary:    #dee1f9;
      --text-secondary:  #bbc9cd;
      --text-muted:      #4a5568;
      --cyan-mid:        #22d3ee;
      --cyan-primary:    #8aebff;
      --cyan-bright:     #2fd9f4;
      --violet-primary:  #d0bcff;
      --violet-deep:     #8b5cf6;
      --blue-mid:        #adc6ff;
      --green:           #4ade80;
      --red:             #ff5f57;
      --yellow:          #ffbd2e;
      --green-dot:       #28c840;
      --border-subtle:   rgba(255,255,255,0.07);
      --border-elevated: rgba(255,255,255,0.14);
      --gradient-cta:    linear-gradient(135deg, #22d3ee 0%, #8b5cf6 100%);
      --radius-sm:  4px;  --radius-md: 12px;
      --radius-lg: 16px;  --radius-xl: 24px;
      --radius-full: 9999px;
    }

    html, body { height: 100%; overflow: hidden; }

    body {
      font-family: 'Inter', -apple-system, sans-serif;
      background: var(--bg-base);
      color: var(--text-primary);
      display: flex; flex-direction: column;
    }

    body::before {
      content: ''; position: fixed; inset: 0;
      background:
        radial-gradient(ellipse 55% 50% at 65% 35%, rgba(34,211,238,0.055) 0%, transparent 70%),
        radial-gradient(ellipse 45% 55% at 30% 70%, rgba(139,92,246,0.045) 0%, transparent 70%);
      pointer-events: none; z-index: 0;
    }

    /* ===========================
       APP HEADER
    =========================== */
    .app-header {
      position: relative; z-index: 50;
      height: 60px; flex-shrink: 0;
      background: rgba(11,16,32,0.92);
      backdrop-filter: blur(16px);
      -webkit-backdrop-filter: blur(16px);
      border-bottom: 1px solid rgba(255,255,255,0.07);
      display: flex; align-items: center;
      justify-content: space-between;
      padding: 0 24px;
    }

    .header-left {
      display: flex; align-items: center; gap: 12px;
    }

    .header-logo {
      display: flex; align-items: center; gap: 8px;
      text-decoration: none;
    }

    .header-logo svg { width: 28px; height: 28px; }

    .header-logo-text {
      font-size: 15px; font-weight: 700;
      color: var(--text-primary); letter-spacing: -0.02em;
    }

    .header-badge {
      display: inline-flex; align-items: center; gap: 5px;
      padding: 3px 10px;
      background: rgba(34,211,238,0.08);
      border: 1px solid rgba(34,211,238,0.2);
      border-radius: var(--radius-full);
      font-family: 'Geist Mono', monospace;
      font-size: 10px; font-weight: 600;
      color: var(--cyan-mid);
      letter-spacing: 0.08em; text-transform: uppercase;
    }

    .header-nav {
      display: flex; align-items: center; gap: 4px;
    }

    .hnav-tab {
      padding: 7px 16px;
      border-radius: var(--radius-full);
      font-size: 13px; font-weight: 500;
      color: var(--text-secondary);
      background: none; border: none;
      cursor: pointer;
      transition: background 0.2s, color 0.2s;
    }
    .hnav-tab:hover { background: rgba(255,255,255,0.05); color: var(--text-primary); }
    .hnav-tab.active {
      background: rgba(255,255,255,0.07);
      color: var(--text-primary); font-weight: 600;
    }

    .header-right {
      display: flex; align-items: center; gap: 14px;
    }

    .header-icon-btn {
      width: 34px; height: 34px;
      border-radius: var(--radius-md);
      display: flex; align-items: center; justify-content: center;
      background: none; border: none; cursor: pointer;
      color: var(--text-secondary);
      transition: background 0.2s, color 0.2s;
    }
    .header-icon-btn:hover { background: rgba(255,255,255,0.06); color: var(--text-primary); }

    .header-avatar {
      width: 32px; height: 32px; border-radius: 50%;
      background: var(--gradient-cta);
      display: flex; align-items: center; justify-content: center;
      font-size: 12px; font-weight: 700; color: #000;
      cursor: pointer; flex-shrink: 0;
    }

    /* ===========================
       APP SHELL
    =========================== */
    .app-shell {
      flex: 1; display: flex;
      overflow: hidden; position: relative; z-index: 1;
    }

    /* ===========================
       LEFT SIDEBAR
    =========================== */
    .sidebar {
      width: 280px; flex-shrink: 0;
      background: rgba(10,13,24,0.85);
      border-right: 1px solid rgba(255,255,255,0.06);
      display: flex; flex-direction: column;
      overflow: hidden;
    }

    .sidebar-header {
      padding: 18px 16px 14px;
      border-bottom: 1px solid rgba(255,255,255,0.05);
      flex-shrink: 0;
    }

    .sidebar-title-row {
      display: flex; align-items: center;
      justify-content: space-between; margin-bottom: 12px;
    }

    .sidebar-title {
      font-size: 13px; font-weight: 600;
      color: var(--text-primary);
    }

    .sidebar-version-badge {
      font-family: 'Geist Mono', monospace;
      font-size: 10px; font-weight: 600;
      color: var(--green); letter-spacing: 0.04em;
      background: rgba(74,222,128,0.1);
      border: 1px solid rgba(74,222,128,0.22);
      border-radius: var(--radius-full);
      padding: 2px 8px;
    }

    .sidebar-search {
      width: 100%;
      background: rgba(255,255,255,0.04);
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: 10px;
      padding: 9px 12px 9px 34px;
      color: var(--text-primary);
      font-size: 13px; font-family: 'Inter', sans-serif;
      outline: none;
      transition: border-color 0.2s, box-shadow 0.2s;
      position: relative;
    }
    .sidebar-search:focus {
      border-color: rgba(34,211,238,0.35);
      box-shadow: 0 0 0 3px rgba(34,211,238,0.08);
    }
    .sidebar-search::placeholder { color: var(--text-muted); }

    .search-wrap { position: relative; }
    .search-icon {
      position: absolute; left: 10px; top: 50%;
      transform: translateY(-50%);
      color: var(--text-muted); pointer-events: none;
    }

    /* Schema tree */
    .schema-tree { flex: 1; overflow-y: auto; padding: 10px 8px; }
    .schema-tree::-webkit-scrollbar { width: 4px; }
    .schema-tree::-webkit-scrollbar-track { background: transparent; }
    .schema-tree::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.08); border-radius: 2px; }

    .table-group { margin-bottom: 4px; }

    .table-header {
      display: flex; align-items: center;
      gap: 8px; padding: 8px 10px;
      border-radius: 9px; cursor: pointer;
      transition: background 0.15s;
      user-select: none;
    }
    .table-header:hover { background: rgba(34,211,238,0.06); }

    .table-chevron {
      color: var(--text-muted); font-size: 10px;
      transition: transform 0.2s; flex-shrink: 0;
      margin-left: auto;
    }
    .table-chevron.open { transform: rotate(0deg); }
    .table-chevron.closed { transform: rotate(-90deg); }

    .table-icon { flex-shrink: 0; }
    .table-name {
      font-size: 13px; font-weight: 600;
      color: var(--text-primary); flex: 1;
    }

    .table-fields { padding-left: 16px; overflow: hidden; }

    .field-row {
      display: flex; align-items: center;
      gap: 8px; padding: 6px 10px;
      border-radius: 7px;
      transition: background 0.15s; cursor: default;
    }
    .field-row:hover { background: rgba(34,211,238,0.05); }

    .field-type-icon {
      font-family: 'Geist Mono', monospace;
      font-size: 10px; font-weight: 600;
      width: 18px; text-align: center;
      flex-shrink: 0;
    }
    .fti-int  { color: var(--cyan-mid); }
    .fti-varchar { color: var(--violet-primary); }
    .fti-ts   { color: #fbbf24; }
    .fti-dec  { color: var(--green); }

    .field-name {
      font-family: 'Geist Mono', monospace;
      font-size: 12px; color: var(--text-secondary); flex: 1;
    }
    .field-type-label {
      font-family: 'Geist Mono', monospace;
      font-size: 10px; color: var(--text-muted);
      letter-spacing: 0.03em; flex-shrink: 0;
    }

    /* Sidebar footer */
    .sidebar-footer {
      padding: 14px 12px;
      border-top: 1px solid rgba(255,255,255,0.06);
      flex-shrink: 0;
    }

    .db-status-card {
      display: flex; align-items: center; gap: 10px;
      padding: 12px 14px; margin-bottom: 10px;
      background: rgba(74,222,128,0.05);
      border: 1px solid rgba(74,222,128,0.18);
      border-radius: var(--radius-md);
    }

    .pulse-dot {
      width: 8px; height: 8px; border-radius: 50%;
      background: var(--green); flex-shrink: 0;
      animation: pulse-green 2s infinite;
    }
    @keyframes pulse-green {
      0%   { box-shadow: 0 0 0 0 rgba(74,222,128,0.5); }
      70%  { box-shadow: 0 0 0 7px rgba(74,222,128,0); }
      100% { box-shadow: 0 0 0 0 rgba(74,222,128,0); }
    }

    .db-status-text { flex: 1; }
    .db-status-title {
      font-size: 12px; font-weight: 600; color: var(--text-primary);
    }
    .db-status-sub {
      font-family: 'Geist Mono', monospace;
      font-size: 10px; font-weight: 600;
      color: var(--green); letter-spacing: 0.06em;
      text-transform: uppercase;
    }

    .btn-upgrade {
      width: 100%; padding: 9px 0;
      background: rgba(139,92,246,0.08);
      border: 1px solid rgba(139,92,246,0.25);
      border-radius: var(--radius-lg);
      color: var(--violet-primary);
      font-size: 13px; font-weight: 600;
      font-family: 'Inter', sans-serif;
      cursor: pointer; text-align: center;
      transition: background 0.2s, border-color 0.2s;
    }
    .btn-upgrade:hover {
      background: rgba(139,92,246,0.14);
      border-color: rgba(139,92,246,0.4);
    }

    /* ===========================
       MAIN WORKSPACE
    =========================== */
    .workspace {
      flex: 1; overflow-y: auto;
      padding: 28px 32px;
      display: flex; flex-direction: column; gap: 20px;
    }
    .workspace::-webkit-scrollbar { width: 5px; }
    .workspace::-webkit-scrollbar-track { background: transparent; }
    .workspace::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.08); border-radius: 3px; }

    /* Mode tabs */
    .mode-tabs-row {
      display: flex; justify-content: center;
    }

    .mode-tabs {
      display: inline-flex;
      background: rgba(255,255,255,0.04);
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: var(--radius-full);
      padding: 4px; gap: 2px;
    }

    .mode-tab {
      display: flex; align-items: center; gap: 7px;
      padding: 9px 22px;
      border-radius: var(--radius-full);
      font-size: 14px; font-weight: 500;
      color: var(--text-secondary);
      background: none; border: none; cursor: pointer;
      transition: all 0.25s ease;
      white-space: nowrap;
    }
    .mode-tab:hover { color: var(--text-primary); }
    .mode-tab.active {
      background: var(--gradient-cta);
      color: #020617; font-weight: 600;
      box-shadow: 0 0 24px rgba(34,211,238,0.28);
    }

    /* Input card */
    .input-card {
      background: rgba(255,255,255,0.03);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border: 1px solid rgba(255,255,255,0.08);
      border-top: 1px solid rgba(255,255,255,0.12);
      border-radius: 20px;
      padding: 20px 24px;
      transition: border-color 0.3s;
    }
    .input-card:focus-within {
      border-color: rgba(34,211,238,0.25);
      box-shadow: 0 0 0 1px rgba(34,211,238,0.06);
    }

    .main-textarea {
      width: 100%; min-height: 84px;
      background: none; border: none;
      resize: none; outline: none;
      font-family: 'Inter', sans-serif;
      font-size: 15px; font-weight: 400;
      color: var(--text-primary); line-height: 1.65;
    }
    .main-textarea::placeholder { color: rgba(187,201,205,0.45); }

    .input-bottom-row {
      display: flex; align-items: center;
      justify-content: space-between;
      margin-top: 14px; padding-top: 14px;
      border-top: 1px solid rgba(255,255,255,0.06);
      flex-wrap: wrap; gap: 12px;
    }

    .input-left-tools {
      display: flex; align-items: center; gap: 10px;
    }

    .tool-icon-btn {
      width: 32px; height: 32px;
      display: flex; align-items: center; justify-content: center;
      background: rgba(255,255,255,0.05);
      border: 1px solid rgba(255,255,255,0.08);
      border-radius: 9px; cursor: pointer; color: var(--text-secondary);
      transition: background 0.2s, color 0.2s;
    }
    .tool-icon-btn:hover { background: rgba(255,255,255,0.08); color: var(--text-primary); }

    .tools-divider {
      width: 1px; height: 22px;
      background: rgba(255,255,255,0.1);
    }

    .toggle-group {
      display: flex; align-items: center; gap: 8px;
    }

    .toggle-label {
      font-family: 'Geist Mono', monospace;
      font-size: 12px; font-weight: 500;
      color: var(--text-secondary);
    }

    .toggle-switch {
      position: relative; width: 36px; height: 20px;
      display: inline-block;
    }
    .toggle-switch input { opacity: 0; width: 0; height: 0; }

    .toggle-track {
      position: absolute; inset: 0; cursor: pointer;
      background: rgba(255,255,255,0.1);
      border-radius: 20px; transition: background 0.25s;
    }
    .toggle-switch input:checked + .toggle-track {
      background: linear-gradient(135deg, #22d3ee, #8b5cf6);
    }
    .toggle-track::after {
      content: ''; position: absolute;
      left: 2px; top: 2px;
      width: 16px; height: 16px;
      border-radius: 50%; background: white;
      transition: transform 0.25s;
      box-shadow: 0 1px 3px rgba(0,0,0,0.4);
    }
    .toggle-switch input:checked + .toggle-track::after {
      transform: translateX(16px);
    }

    .btn-generate {
      display: flex; align-items: center; gap: 8px;
      padding: 11px 24px;
      background: var(--gradient-cta);
      border: none; border-radius: var(--radius-lg);
      color: #020617; font-size: 14px; font-weight: 600;
      font-family: 'Inter', sans-serif;
      cursor: pointer; white-space: nowrap;
      transition: transform 0.2s, box-shadow 0.2s;
      position: relative; overflow: hidden;
    }
    .btn-generate:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 28px rgba(34,211,238,0.4);
    }
    .btn-generate.loading { pointer-events: none; }
    .btn-generate.loading .btn-gen-text { opacity: 0; }
    .btn-generate.loading .btn-gen-spinner { display: block; }
    .btn-gen-spinner {
      display: none; position: absolute;
      width: 16px; height: 16px;
      border: 2px solid rgba(0,0,0,0.3);
      border-top-color: #000;
      border-radius: 50%;
      animation: spin 0.7s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    /* Quick queries */
    .quick-queries-row {
      display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
    }

    .qq-label {
      font-family: 'Geist Mono', monospace;
      font-size: 11px; font-weight: 600;
      color: var(--text-muted);
      letter-spacing: 0.08em; text-transform: uppercase;
      flex-shrink: 0;
    }

    .qq-tag {
      display: flex; align-items: center; gap: 6px;
      padding: 6px 14px;
      background: rgba(255,255,255,0.05);
      border: 1px solid rgba(255,255,255,0.09);
      border-radius: var(--radius-full);
      font-family: 'Geist Mono', monospace;
      font-size: 12px; color: var(--text-secondary);
      cursor: pointer; white-space: nowrap;
      transition: background 0.2s, border-color 0.2s, color 0.2s;
    }
    .qq-tag:hover {
      background: rgba(34,211,238,0.08);
      border-color: rgba(34,211,238,0.3);
      color: var(--cyan-primary);
    }

    /* SQL Output Card */
    .result-zone { display: flex; flex-direction: column; gap: 0; }

    .result-label {
      font-family: 'Geist Mono', monospace;
      font-size: 11px; font-weight: 600;
      color: var(--text-muted);
      letter-spacing: 0.08em; text-transform: uppercase;
      margin-bottom: 10px;
    }

    .sql-output-card {
      background: rgba(7,11,22,0.82);
      backdrop-filter: blur(20px);
      -webkit-backdrop-filter: blur(20px);
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: var(--radius-lg);
      overflow: hidden;
      box-shadow: 0 0 0 1px rgba(34,211,238,0.08), 0 8px 32px rgba(0,0,0,0.4);
    }

    .sql-card-header {
      display: flex; align-items: center;
      justify-content: space-between;
      padding: 12px 16px;
      background: rgba(255,255,255,0.025);
      border-bottom: 1px solid rgba(255,255,255,0.07);
    }

    .sql-header-left {
      display: flex; align-items: center; gap: 10px;
    }

    .window-dots { display: flex; gap: 5px; }
    .wd { width: 10px; height: 10px; border-radius: 50%; }
    .wd.r { background: #ff5f57; }
    .wd.y { background: #ffbd2e; }
    .wd.g { background: #28c840; }

    .sql-filename {
      font-family: 'Geist Mono', monospace;
      font-size: 12px; color: var(--text-secondary);
      display: flex; align-items: center; gap: 6px;
    }

    .sql-header-actions {
      display: flex; align-items: center; gap: 8px;
    }

    .action-btn {
      display: flex; align-items: center; gap: 6px;
      padding: 6px 12px;
      background: rgba(255,255,255,0.05);
      border: 1px solid rgba(255,255,255,0.09);
      border-radius: 8px;
      font-size: 12px; font-weight: 500;
      color: var(--text-secondary);
      font-family: 'Inter', sans-serif;
      cursor: pointer;
      transition: background 0.2s, color 0.2s, border-color 0.2s;
    }
    .action-btn:hover {
      background: rgba(255,255,255,0.08); color: var(--text-primary);
      border-color: rgba(255,255,255,0.15);
    }
    .action-btn.copied {
      color: var(--green); border-color: rgba(74,222,128,0.3);
      background: rgba(74,222,128,0.06);
    }

    .sql-code-block {
      padding: 20px 24px;
      overflow-x: auto;
    }
    .sql-code-block::-webkit-scrollbar { height: 4px; }
    .sql-code-block::-webkit-scrollbar-track { background: transparent; }
    .sql-code-block::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); border-radius: 2px; }

    pre { margin: 0; white-space: pre; }
    code {
      font-family: 'Geist Mono', monospace;
      font-size: 13px; line-height: 1.8;
    }

    /* SQL syntax */
    .k { color: #c4abff; }
    .f { color: #22d3ee; }
    .s { color: #86efac; }
    .n { color: #fca5a5; }
    .c { color: #dee1f9; }
    .cm { color: #3d4b5c; font-style: italic; }
    .op { color: #c4abff; }

    .sql-footer {
      display: flex; align-items: center;
      justify-content: space-between;
      padding: 12px 16px;
      border-top: 1px solid rgba(255,255,255,0.06);
    }

    .explain-toggle-btn {
      display: flex; align-items: center; gap: 7px;
      padding: 7px 14px;
      background: rgba(139,92,246,0.08);
      border: 1px solid rgba(139,92,246,0.2);
      border-radius: var(--radius-full);
      color: var(--violet-primary);
      font-size: 12px; font-weight: 600;
      font-family: 'Inter', sans-serif;
      cursor: pointer;
      transition: background 0.2s, border-color 0.2s;
    }
    .explain-toggle-btn:hover {
      background: rgba(139,92,246,0.14);
      border-color: rgba(139,92,246,0.35);
    }

    .explain-chevron {
      transition: transform 0.25s; font-size: 10px;
    }
    .explain-chevron.open { transform: rotate(180deg); }

    .sql-row-count {
      font-family: 'Geist Mono', monospace;
      font-size: 11px; color: var(--text-muted);
    }

    /* Explanation Timeline */
    .timeline-section {
      background: rgba(255,255,255,0.02);
      border: 1px solid rgba(255,255,255,0.06);
      border-radius: var(--radius-lg);
      padding: 24px;
      overflow: hidden;
      max-height: 0;
      transition: max-height 0.4s ease, opacity 0.3s ease, padding 0.3s ease;
      opacity: 0;
    }
    .timeline-section.open {
      max-height: 600px; opacity: 1;
    }

    .timeline-title {
      font-size: 13px; font-weight: 600;
      color: var(--text-primary); margin-bottom: 20px;
      display: flex; align-items: center; gap: 8px;
    }

    .timeline {
      border-left: 2px solid rgba(34,211,238,0.2);
      padding-left: 20px;
      display: flex; flex-direction: column; gap: 0;
    }

    .step-item {
      position: relative; padding-bottom: 22px;
    }
    .step-item:last-child { padding-bottom: 0; }

    .step-dot {
      position: absolute;
      left: -26px; top: 4px;
      width: 10px; height: 10px;
      border-radius: 50%;
      background: linear-gradient(135deg, #22d3ee, #8b5cf6);
      box-shadow: 0 0 8px rgba(34,211,238,0.4);
    }

    .step-num {
      font-family: 'Geist Mono', monospace;
      font-size: 10px; font-weight: 600;
      color: var(--cyan-mid); letter-spacing: 0.08em;
      text-transform: uppercase; margin-bottom: 4px;
    }

    .step-title {
      font-size: 14px; font-weight: 600;
      color: var(--text-primary); margin-bottom: 4px;
    }

    .step-body {
      font-size: 13px; color: var(--text-secondary);
      line-height: 1.65;
    }
    .step-body .hl { color: var(--cyan-mid); font-weight: 500; }

    /* Toast */
    .toast {
      position: fixed; bottom: 28px; right: 28px; z-index: 999;
      display: flex; align-items: center; gap: 10px;
      padding: 12px 20px;
      background: rgba(22,27,43,0.95);
      border: 1px solid rgba(74,222,128,0.3);
      border-radius: var(--radius-lg);
      box-shadow: 0 8px 32px rgba(0,0,0,0.5);
      font-size: 13px; font-weight: 500;
      color: var(--text-primary);
      backdrop-filter: blur(16px);
      transform: translateY(80px); opacity: 0;
      transition: transform 0.3s ease, opacity 0.3s ease;
    }
    .toast.show { transform: translateY(0); opacity: 1; }
    .toast-dot { width: 7px; height: 7px; border-radius: 50%; background: var(--green); flex-shrink: 0; }
  </style>
</head>
<body>

  <!-- ===== APP HEADER ===== -->
  <header class="app-header">
    <div class="header-left">
      <a href="/" class="header-logo">
        <svg viewBox="0 0 28 28" fill="none">
          <rect width="28" height="28" rx="7" fill="url(#hg1)"/>
          <path d="M6 15l3-4.5L12 16l2.5-6L18 17l3-4.5" stroke="white" stroke-width="1.6"
                stroke-linecap="round" stroke-linejoin="round"/>
          <defs>
            <linearGradient id="hg1" x1="0" y1="0" x2="28" y2="28">
              <stop offset="0%" stop-color="#22d3ee"/>
              <stop offset="100%" stop-color="#8b5cf6"/>
            </linearGradient>
          </defs>
        </svg>
        <span class="header-logo-text">QueryMind AI</span>
      </a>
      <span class="header-badge">&#x2736; AI POWERED V1.0</span>
    </div>

    <nav class="header-nav">
      <button class="hnav-tab active">Query</button>
      <button class="hnav-tab">Dashboards</button>
      <button class="hnav-tab">Notebooks</button>
    </nav>

    <div class="header-right">
      <button class="header-icon-btn" title="Notifications">
        <svg width="17" height="17" viewBox="0 0 17 17" fill="none">
          <path d="M8.5 2a5.5 5.5 0 015.5 5.5v2l1 2H2l1-2V7.5A5.5 5.5 0 018.5 2z" stroke="currentColor" stroke-width="1.4"/>
          <path d="M7 14a1.5 1.5 0 003 0" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
        </svg>
      </button>
      <button class="header-icon-btn" title="Settings">
        <svg width="17" height="17" viewBox="0 0 17 17" fill="none">
          <circle cx="8.5" cy="8.5" r="2.5" stroke="currentColor" stroke-width="1.4"/>
          <path d="M8.5 1.5v2M8.5 13.5v2M1.5 8.5h2M13.5 8.5h2M3.4 3.4l1.4 1.4M12.2 12.2l1.4 1.4M3.4 13.6l1.4-1.4M12.2 4.8l1.4-1.4" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
        </svg>
      </button>
      <div class="header-avatar">N</div>
    </div>
  </header>

  <!-- ===== APP SHELL ===== -->
  <div class="app-shell">

    <!-- ===== LEFT SIDEBAR ===== -->
    <aside class="sidebar">
      <div class="sidebar-header">
        <div class="sidebar-title-row">
          <span class="sidebar-title">Database Schema</span>
          <span class="sidebar-version-badge">v2.4 Stable</span>
        </div>
        <div class="search-wrap">
          <svg class="search-icon" width="13" height="13" viewBox="0 0 13 13" fill="none">
            <circle cx="5.5" cy="5.5" r="4" stroke="#4a5568" stroke-width="1.4"/>
            <path d="M9 9l2.5 2.5" stroke="#4a5568" stroke-width="1.4" stroke-linecap="round"/>
          </svg>
          <input class="sidebar-search" type="text" placeholder="Search tables...">
        </div>
      </div>

      <div class="schema-tree">

        <!-- Table: merchants -->
        <div class="table-group" id="tg-merchants">
          <div class="table-header" onclick="toggleTable('merchants')">
            <svg class="table-icon" width="14" height="14" viewBox="0 0 14 14" fill="none">
              <rect x="1" y="2" width="12" height="10" rx="2" stroke="#22d3ee" stroke-width="1.4"/>
              <path d="M1 6h12M5 6v6" stroke="#22d3ee" stroke-width="1.3"/>
            </svg>
            <span class="table-name">merchants</span>
            <svg class="table-chevron open" id="chev-merchants" width="10" height="10" viewBox="0 0 10 10" fill="none">
              <path d="M2 4l3 3 3-3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </div>
          <div class="table-fields" id="fields-merchants">
            <div class="field-row">
              <span class="field-type-icon fti-int">#</span>
              <span class="field-name">id</span>
              <span class="field-type-label">INT</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-varchar">T</span>
              <span class="field-name">name</span>
              <span class="field-type-label">VARCHAR</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-varchar">T</span>
              <span class="field-name">category</span>
              <span class="field-type-label">VARCHAR</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-dec">&#x2248;</span>
              <span class="field-name">amount</span>
              <span class="field-type-label">DECIMAL</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-ts">&#x23F1;</span>
              <span class="field-name">created_at</span>
              <span class="field-type-label">TIMESTAMP</span>
            </div>
          </div>
        </div>

        <!-- Table: transactions -->
        <div class="table-group" id="tg-transactions">
          <div class="table-header" onclick="toggleTable('transactions')">
            <svg class="table-icon" width="14" height="14" viewBox="0 0 14 14" fill="none">
              <rect x="1" y="2" width="12" height="10" rx="2" stroke="#22d3ee" stroke-width="1.4"/>
              <path d="M1 6h12M5 6v6" stroke="#22d3ee" stroke-width="1.3"/>
            </svg>
            <span class="table-name">transactions</span>
            <svg class="table-chevron open" id="chev-transactions" width="10" height="10" viewBox="0 0 10 10" fill="none">
              <path d="M2 4l3 3 3-3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </div>
          <div class="table-fields" id="fields-transactions">
            <div class="field-row">
              <span class="field-type-icon fti-int">#</span>
              <span class="field-name">id</span>
              <span class="field-type-label">INT</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-int">#</span>
              <span class="field-name">merchant_id</span>
              <span class="field-type-label">INT</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-varchar">T</span>
              <span class="field-name">name</span>
              <span class="field-type-label">VARCHAR</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-dec">&#x2248;</span>
              <span class="field-name">amount</span>
              <span class="field-type-label">DECIMAL</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-varchar">T</span>
              <span class="field-name">status</span>
              <span class="field-type-label">VARCHAR</span>
            </div>
            <div class="field-row">
              <span class="field-type-icon fti-ts">&#x23F1;</span>
              <span class="field-name">created_at</span>
              <span class="field-type-label">TIMESTAMP</span>
            </div>
          </div>
        </div>

      </div><!-- end schema-tree -->

      <div class="sidebar-footer">
        <div class="db-status-card">
          <div class="pulse-dot"></div>
          <div class="db-status-text">
            <div class="db-status-title">Connected to Production DB</div>
            <div class="db-status-sub">LIVE SYNC ENABLED</div>
          </div>
        </div>
        <button class="btn-upgrade">&#x26A1; Upgrade to Pro</button>
      </div>
    </aside>

    <!-- ===== MAIN WORKSPACE ===== -->
    <main class="workspace">

      <!-- Mode Tabs -->
      <div class="mode-tabs-row">
        <div class="mode-tabs">
          <button class="mode-tab active" id="tab-translate" onclick="switchMode('translate')">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <path d="M1 3h6M4 3v8M7 10H1M8 3l2 4 2-4M9 6h2" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            Translate Vietnamese to SQL
          </button>
          <button class="mode-tab" id="tab-explain" onclick="switchMode('explain')">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <circle cx="7" cy="7" r="5.5" stroke="currentColor" stroke-width="1.4"/>
              <path d="M7 6v4M7 4.5v.5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
            </svg>
            Explain SQL Query
          </button>
        </div>
      </div>

      <!-- Input Zone -->
      <div class="input-card">
        <textarea
          class="main-textarea"
          id="main-input"
          placeholder="V&#xED; d&#x1EE5;: L&#x1EA5;y t&#x1ED5;ng doanh thu c&#x1EE7;a t&#x1EEB;ng merchant trong th&#xE1;ng n&#xE0;y, s&#x1EAF;p x&#x1EBF;p t&#x1EEB; cao &#x111;&#x1EBF;n th&#x1EA5;p..."
          rows="4"
        >L&#x1EA5;y danh s&#xE1;ch top 10 merchant theo t&#x1ED5;ng doanh thu th&#xE1;ng n&#xE0;y, ch&#x1EC9; t&#xED;nh giao d&#x1ECB;ch th&#xE0;nh c&#xF4;ng</textarea>

        <div class="input-bottom-row">
          <div class="input-left-tools">
            <button class="tool-icon-btn" title="Voice input">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <rect x="4.5" y="1" width="5" height="7" rx="2.5" stroke="currentColor" stroke-width="1.4"/>
                <path d="M2 7a5 5 0 0010 0" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
                <path d="M7 12v2" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
              </svg>
            </button>
            <button class="tool-icon-btn" title="Attach file">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M12 6.5l-5.5 5.5a3.5 3.5 0 01-5-5l6-6a2 2 0 013 3L4 10a1 1 0 01-1.5-1.5L8 3" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </button>
            <div class="tools-divider"></div>
            <div class="toggle-group">
              <label class="toggle-switch">
                <input type="checkbox" checked id="schema-toggle">
                <span class="toggle-track"></span>
              </label>
              <span class="toggle-label">Schema-aware</span>
            </div>
            <div class="toggle-group">
              <label class="toggle-switch">
                <input type="checkbox" id="optimize-toggle">
                <span class="toggle-track"></span>
              </label>
              <span class="toggle-label">Auto-optimize</span>
            </div>
          </div>

          <button class="btn-generate" id="gen-btn" onclick="generateInsight()">
            <div class="btn-gen-spinner"></div>
            <span class="btn-gen-text">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none" style="vertical-align:middle;margin-right:5px;">
                <path d="M7 1l1.5 4.5H13l-3.75 2.72 1.44 4.42L7 10.14 3.31 12.64l1.44-4.42L1 5.5h4.5z" fill="currentColor"/>
              </svg>
              Generate Insight
            </span>
          </button>
        </div>
      </div>

      <!-- Quick Queries -->
      <div class="quick-queries-row">
        <span class="qq-label">Quick Queries:</span>
        <button class="qq-tag" onclick="fillQuery('gmv')">&#x26A1; Top Merchants by GMV</button>
        <button class="qq-tag" onclick="fillQuery('growth')">&#x1F4C8; Fast Growth List</button>
        <button class="qq-tag" onclick="fillQuery('failure')">&#x26A0; Failure Rate Analysis</button>
      </div>

      <!-- SQL Output Card -->
      <div class="result-zone">
        <div class="result-label">Generated SQL Output</div>
        <div class="sql-output-card" id="sql-card">
          <div class="sql-card-header">
            <div class="sql-header-left">
              <div class="window-dots">
                <div class="wd r"></div>
                <div class="wd y"></div>
                <div class="wd g"></div>
              </div>
              <span class="sql-filename">
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                  <rect x="1" y="1" width="10" height="10" rx="2" stroke="#bbc9cd" stroke-width="1.2"/>
                  <path d="M3 4h6M3 6h4M3 8h5" stroke="#bbc9cd" stroke-width="1.1" stroke-linecap="round"/>
                </svg>
                query_v1_insight.sql
              </span>
            </div>
            <div class="sql-header-actions">
              <button class="action-btn" id="copy-btn" onclick="copyCode()">
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                  <rect x="4" y="4" width="7" height="7" rx="1.5" stroke="currentColor" stroke-width="1.3"/>
                  <path d="M8 4V3a1 1 0 00-1-1H3a1 1 0 00-1 1v4a1 1 0 001 1h1" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>
                </svg>
                Copy Code
              </button>
              <button class="action-btn" onclick="downloadSQL()">
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                  <path d="M6 1v7M3 5l3 3 3-3M1 9v1a1 1 0 001 1h8a1 1 0 001-1V9" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                Download .sql
              </button>
            </div>
          </div>

          <div class="sql-code-block">
            <pre><code id="sql-output"><span class="cm">-- Generated by QueryMind AI</span>
<span class="k">SELECT</span>
    <span class="c">m</span>.<span class="c">name</span> <span class="k">AS</span> <span class="c">merchant_name</span>,
    <span class="f">SUM</span>(<span class="c">t</span>.<span class="c">amount</span>) <span class="k">AS</span> <span class="c">total_revenue</span>
<span class="k">FROM</span>
    <span class="c">merchants</span> <span class="c">m</span>
<span class="k">JOIN</span> <span class="c">transactions</span> <span class="c">t</span>
    <span class="k">ON</span> <span class="c">m</span>.<span class="c">id</span> <span class="op">=</span> <span class="c">t</span>.<span class="c">merchant_id</span>
<span class="k">WHERE</span>
    <span class="c">t</span>.<span class="c">created_at</span> <span class="op">&gt;=</span> <span class="f">DATE_TRUNC</span>(<span class="s">'month'</span>, <span class="f">CURRENT_DATE</span>)
    <span class="k">AND</span> <span class="c">t</span>.<span class="c">created_at</span> <span class="op">&lt;</span> <span class="f">DATE_TRUNC</span>(<span class="s">'month'</span>, <span class="f">CURRENT_DATE</span>) <span class="op">+</span> <span class="f">INTERVAL</span> <span class="s">'1 month'</span>
    <span class="k">AND</span> <span class="c">t</span>.<span class="c">status</span> <span class="op">=</span> <span class="s">'completed'</span>
<span class="k">GROUP BY</span>
    <span class="c">m</span>.<span class="c">id</span>, <span class="c">m</span>.<span class="c">name</span>
<span class="k">ORDER BY</span>
    <span class="c">total_revenue</span> <span class="k">DESC</span>
<span class="k">LIMIT</span> <span class="n">10</span>;</code></pre>
          </div>

          <div class="sql-footer">
            <button class="explain-toggle-btn" onclick="toggleExplain()">
              <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                <path d="M2 4l4 4 4-4" id="explain-chev-path" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              Explain Every Step
              <span class="explain-chevron" id="explain-chevron">&#x25BE;</span>
            </button>
            <span class="sql-row-count">&#x2713; Valid SQL &#xB7; 13 lines</span>
          </div>
        </div>

        <!-- Explanation Timeline -->
        <div class="timeline-section" id="timeline-section">
          <div class="timeline-title">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <circle cx="7" cy="7" r="5.5" stroke="#22d3ee" stroke-width="1.4"/>
              <path d="M7 4v3.5L9 9" stroke="#22d3ee" stroke-width="1.4" stroke-linecap="round"/>
            </svg>
            Step-by-Step Explanation
          </div>
          <div class="timeline">
            <div class="step-item">
              <div class="step-dot"></div>
              <div class="step-num">Step 1</div>
              <div class="step-title">L&#x1ECD;c d&#x1EEF; li&#x1EC7;u theo th&#x1EDD;i gian v&#xE0; tr&#x1EA1;ng th&#xE1;i</div>
              <div class="step-body">
                M&#x1EC7;nh &#x111;&#x1EC1; <span class="hl">WHERE</span> l&#x1ECD;c b&#x1EA3;ng <span class="hl">transactions</span> &#x111;&#x1EC3; ch&#x1EC9; l&#x1EA5;y c&#xE1;c giao d&#x1ECB;ch
                trong th&#xE1;ng hi&#x1EC7;n t&#x1EA1;i b&#x1EB1;ng h&#xE0;m <span class="hl">DATE_TRUNC('month', CURRENT_DATE)</span>.
                &#x110;&#x1ED3;ng th&#x1EDD;i, ch&#x1EC9; t&#xED;nh giao d&#x1ECB;ch c&#xF3; <span class="hl">status = 'completed'</span> &#x2014; b&#x1ECF; qua giao d&#x1ECB;ch &#x111;ang ch&#x1EDD; ho&#x1EB7;c th&#x1EA5;t b&#x1EA1;i.
              </div>
            </div>
            <div class="step-item">
              <div class="step-dot"></div>
              <div class="step-num">Step 2</div>
              <div class="step-title">K&#x1EBF;t h&#x1EE3;p d&#x1EEF; li&#x1EC7;u t&#x1EEB; hai b&#x1EA3;ng</div>
              <div class="step-body">
                C&#xE2;u l&#x1EC7;nh <span class="hl">JOIN</span> gh&#x1EB9;p b&#x1EA3;ng <span class="hl">merchants</span> v&#x1EDB;i
                <span class="hl">transactions</span> qua &#x111;i&#x1EC1;u ki&#x1EC7;n <span class="hl">m.id = t.merchant_id</span>,
                cho ph&#xE9;p l&#x1EA5;y t&#xEA;n merchant t&#x1EEB; b&#x1EA3;ng merchants khi t&#xED;nh to&#xE1;n doanh thu t&#x1EEB; b&#x1EA3;ng transactions.
              </div>
            </div>
            <div class="step-item">
              <div class="step-dot"></div>
              <div class="step-num">Step 3</div>
              <div class="step-title">T&#xED;nh t&#x1ED5;ng doanh thu theo t&#x1EEB;ng merchant</div>
              <div class="step-body">
                <span class="hl">GROUP BY m.id, m.name</span> nh&#xF3;m t&#x1EA5;t c&#x1EA3; giao d&#x1ECB;ch theo t&#x1EEB;ng merchant.
                H&#xE0;m <span class="hl">SUM(t.amount)</span> c&#x1ED9;ng to&#xE0;n b&#x1ED9; gi&#xE1; tr&#x1ECB; giao d&#x1ECB;ch trong nh&#xF3;m &#x111;&#xF3;,
                &#x111;&#x1EB7;t t&#xEA;n k&#x1EBF;t qu&#x1EA3; l&#xE0; <span class="hl">total_revenue</span> &#x111;&#x1EC3; d&#x1EC5; &#x111;&#x1ECD;c.
              </div>
            </div>
            <div class="step-item">
              <div class="step-dot"></div>
              <div class="step-num">Step 4</div>
              <div class="step-title">S&#x1EAF;p x&#x1EBF;p v&#xE0; gi&#x1EDB;i h&#x1EA1;n k&#x1EBF;t qu&#x1EA3;</div>
              <div class="step-body">
                <span class="hl">ORDER BY total_revenue DESC</span> s&#x1EAF;p x&#x1EBF;p k&#x1EBF;t qu&#x1EA3; t&#x1EEB; merchant c&#xF3; doanh thu cao nh&#x1EA5;t
                xu&#x1ED1;ng th&#x1EA5;p nh&#x1EA5;t. <span class="hl">LIMIT 10</span> ch&#x1EC9; tr&#x1EA3; v&#x1EC1; 10 merchant &#x111;&#x1EE9;ng &#x111;&#x1EA7;u danh s&#xE1;ch.
              </div>
            </div>
          </div>
        </div>
      </div>

    </main><!-- end workspace -->
  </div><!-- end app-shell -->

  <!-- Toast notification -->
  <div class="toast" id="toast">
    <div class="toast-dot"></div>
    <span id="toast-msg">Copied to clipboard!</span>
  </div>

  <script>
    // ===== STATE =====
    let currentMode = 'translate';
    let explainOpen = false;
    let toastTimer = null;

    const QUICK_QUERIES = {
      gmv:     'Lấy danh sách top 10 merchant theo tổng giá trị giao dịch (GMV) cao nhất trong tháng này',
      growth:  'Liệt kê các merchant có tốc độ tăng trưỳng doanh thu nhanh nhất so với tháng trước',
      failure: 'Phân tích tỷ lệ giao dịch thất bại theo từng merchant, sắp xếp từ tỷ lệ cao đến thấp'
    };

    const MOCK_SQL = {
      translate: `<span class="cm">-- Generated by QueryMind AI</span>
<span class="k">SELECT</span>
    <span class="c">m</span>.<span class="c">name</span> <span class="k">AS</span> <span class="c">merchant_name</span>,
    <span class="f">SUM</span>(<span class="c">t</span>.<span class="c">amount</span>) <span class="k">AS</span> <span class="c">total_revenue</span>
<span class="k">FROM</span>
    <span class="c">merchants</span> <span class="c">m</span>
<span class="k">JOIN</span> <span class="c">transactions</span> <span class="c">t</span>
    <span class="k">ON</span> <span class="c">m</span>.<span class="c">id</span> <span class="op">=</span> <span class="c">t</span>.<span class="c">merchant_id</span>
<span class="k">WHERE</span>
    <span class="c">t</span>.<span class="c">created_at</span> <span class="op">&gt;=</span> <span class="f">DATE_TRUNC</span>(<span class="s">'month'</span>, <span class="f">CURRENT_DATE</span>)
    <span class="k">AND</span> <span class="c">t</span>.<span class="c">status</span> <span class="op">=</span> <span class="s">'completed'</span>
<span class="k">GROUP BY</span>
    <span class="c">m</span>.<span class="c">id</span>, <span class="c">m</span>.<span class="c">name</span>
<span class="k">ORDER BY</span>
    <span class="c">total_revenue</span> <span class="k">DESC</span>
<span class="k">LIMIT</span> <span class="n">10</span>;`,
      explain: `<span class="cm">-- Analysis by QueryMind AI</span>
<span class="cm">-- Input query broken into logical components:</span>
<span class="cm">--  Step 1: Filter  → WHERE clause scope</span>
<span class="cm">--  Step 2: Join    → merchants ⟶ transactions</span>
<span class="cm">--  Step 3: Aggregate → SUM(amount) per group</span>
<span class="cm">--  Step 4: Sort & Limit → TOP 10 result set</span>`
    };

    // ===== MODE SWITCH =====
    function switchMode(mode) {
      currentMode = mode;
      document.querySelectorAll('.mode-tab').forEach(t => t.classList.remove('active'));
      document.getElementById('tab-' + mode).classList.add('active');

      const placeholders = {
        translate: 'Ví dụ: Lấy tổng doanh thu của từ\ng merchant trong tháng này, sắp xếp từ cao đến thấp...',
        explain:   'Ví dụ: Dán SQL phức tạp vào đây để QueryMind AI giải thích từng bước một...'
      };
      document.getElementById('main-input').placeholder = placeholders[mode];
    }

    // ===== QUICK QUERIES =====
    function fillQuery(key) {
      document.getElementById('main-input').value = QUICK_QUERIES[key];
      switchMode('translate');
    }

    // ===== GENERATE INSIGHT =====
    function generateInsight() {
      const btn = document.getElementById('gen-btn');
      btn.classList.add('loading');

      if (explainOpen) toggleExplain();

      setTimeout(() => {
        btn.classList.remove('loading');
        document.getElementById('sql-output').innerHTML = MOCK_SQL[currentMode];
        showToast('✓ Query generated successfully');
      }, 1400);
    }

    // ===== SCHEMA TREE TOGGLE =====
    function toggleTable(tableName) {
      const fields = document.getElementById('fields-' + tableName);
      const chev   = document.getElementById('chev-' + tableName);
      const isOpen = chev.classList.contains('open');

      if (isOpen) {
        fields.style.maxHeight = fields.scrollHeight + 'px';
        requestAnimationFrame(() => {
          fields.style.transition = 'max-height 0.25s ease, opacity 0.2s ease';
          fields.style.maxHeight = '0';
          fields.style.opacity = '0';
          fields.style.overflow = 'hidden';
        });
        chev.classList.remove('open');
        chev.classList.add('closed');
      } else {
        fields.style.maxHeight = '0';
        fields.style.overflow = 'hidden';
        requestAnimationFrame(() => {
          fields.style.transition = 'max-height 0.28s ease, opacity 0.2s ease';
          fields.style.maxHeight = fields.scrollHeight + 200 + 'px';
          fields.style.opacity = '1';
        });
        chev.classList.remove('closed');
        chev.classList.add('open');
      }
    }

    // Initialize tree open state
    ['merchants','transactions'].forEach(t => {
      const f = document.getElementById('fields-' + t);
      f.style.overflow = 'hidden';
      f.style.opacity = '1';
    });

    // ===== EXPLAIN TOGGLE =====
    function toggleExplain() {
      explainOpen = !explainOpen;
      const section = document.getElementById('timeline-section');
      const chev    = document.getElementById('explain-chevron');
      section.classList.toggle('open', explainOpen);
      chev.style.transform = explainOpen ? 'rotate(180deg)' : 'rotate(0deg)';
      chev.style.transition = 'transform 0.25s ease';
    }

    // ===== COPY CODE =====
    function copyCode() {
      const codeEl = document.getElementById('sql-output');
      const text   = codeEl.innerText || codeEl.textContent;
      const btn    = document.getElementById('copy-btn');

      navigator.clipboard.writeText(text).then(() => {
        btn.classList.add('copied');
        btn.innerHTML = `<svg width="12" height="12" viewBox="0 0 12 12" fill="none">
          <path d="M2 6l3 3 5-5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg> Copied!`;
        showToast('Code copied to clipboard!');
        setTimeout(() => {
          btn.classList.remove('copied');
          btn.innerHTML = `<svg width="12" height="12" viewBox="0 0 12 12" fill="none">
            <rect x="4" y="4" width="7" height="7" rx="1.5" stroke="currentColor" stroke-width="1.3"/>
            <path d="M8 4V3a1 1 0 00-1-1H3a1 1 0 00-1 1v4a1 1 0 001 1h1" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>
          </svg> Copy Code`;
        }, 2000);
      }).catch(() => showToast('Copy failed — please try manually'));
    }

    // ===== DOWNLOAD SQL =====
    function downloadSQL() {
      const codeEl = document.getElementById('sql-output');
      const text   = codeEl.innerText || codeEl.textContent;
      const blob   = new Blob([text], { type: 'text/plain' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = 'query_v1_insight.sql';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(a.href);
      showToast('Downloading query_v1_insight.sql...');
    }

    // ===== TOAST =====
    function showToast(msg) {
      const toast = document.getElementById('toast');
      document.getElementById('toast-msg').textContent = msg;
      toast.classList.add('show');
      if (toastTimer) clearTimeout(toastTimer);
      toastTimer = setTimeout(() => toast.classList.remove('show'), 3000);
    }

    // ===== HEADER NAV TABS =====
    document.querySelectorAll('.hnav-tab').forEach(tab => {
      tab.addEventListener('click', function() {
        document.querySelectorAll('.hnav-tab').forEach(t => t.classList.remove('active'));
        this.classList.add('active');
      });
    });

    // ===== SIDEBAR SEARCH FILTER =====
    document.querySelector('.sidebar-search').addEventListener('input', function() {
      const q = this.value.toLowerCase();
      document.querySelectorAll('.field-row').forEach(row => {
        const name = row.querySelector('.field-name').textContent.toLowerCase();
        row.style.display = name.includes(q) || q === '' ? '' : 'none';
      });
      document.querySelectorAll('.table-header').forEach(th => {
        const name = th.querySelector('.table-name').textContent.toLowerCase();
        th.closest('.table-group').style.display = name.includes(q) || q === '' ? '' : 'none';
      });
    });
  </script>

</body>
</html>"""


@app.function(
    secrets=[modal.Secret.from_name("anthropic-api-key")],
)
@modal.asgi_app()
def fastapi_app():
    from fastapi import FastAPI, Request
    from fastapi.responses import HTMLResponse, JSONResponse

    web_app = FastAPI(title="QueryMind AI")

    @web_app.get("/", response_class=HTMLResponse)
    async def serve_landing():
        return HTMLResponse(content=HTML_LANDING)

    @web_app.get("/workspace", response_class=HTMLResponse)
    async def serve_workspace():
        return HTMLResponse(content=HTML_WORKSPACE)

    @web_app.post("/api/translate")
    async def api_translate(request: Request):
        try:
            body = await request.json()
            question = body.get("question", "").strip()
            if not question:
                return JSONResponse(
                    {"error": "Missing 'question' field", "code": 400},
                    status_code=400
                )
            raw = call_claude(TRANSLATE_SYSTEM_PROMPT, question)
            sql = parse_sql_from_response(raw)
            return JSONResponse({"sql": sql, "mode": "translate"})
        except Exception as e:
            return JSONResponse({"error": str(e), "code": 500}, status_code=500)

    @web_app.post("/api/explain")
    async def api_explain(request: Request):
        try:
            body = await request.json()
            sql_input = body.get("sql", "").strip()
            if not sql_input:
                return JSONResponse(
                    {"error": "Missing 'sql' field", "code": 400},
                    status_code=400
                )
            raw = call_claude(EXPLAIN_SYSTEM_PROMPT, sql_input)
            steps = parse_steps_from_response(raw)
            return JSONResponse({"steps": steps, "mode": "explain"})
        except Exception as e:
            return JSONResponse({"error": str(e), "code": 500}, status_code=500)

    return web_app


# [SECTION 6] HTML_LANDING  — defined above in module scope (Landing Page)
# [SECTION 7] HTML_WORKSPACE — defined above in module scope (Workspace Page)

# ============================================================
# [SECTION 8] ROUTE HANDLERS
# ============================================================
# All route handlers (serve_landing, serve_workspace, api_translate, api_explain)
# are registered as FastAPI routes inside fastapi_app() in SECTION 5.
# HTML_LANDING and HTML_WORKSPACE module globals are resolved at request time,
# so the full page content defined in SECTION 6 & 7 is always served correctly.
