"""
Shared pytest fixtures for QueryMind AI / Finviet CDP test suite.

Install dependencies:
    pip install pytest pytest-asyncio httpx

Usage:
    pytest tests/ -v --ignore=tests/test_e2e.py
"""
import os
import pytest
import pytest_asyncio
import httpx

# Must set env var BEFORE importing local_dev — it raises SystemExit if missing
os.environ.setdefault("GEMINI_API_KEY", "test-mock-gemini-key-do-not-use")

from local_dev import (
    web_app,
    build_sql_from_filters,
    estimate_audience_sql,
    simulate_audience_estimate,
    parse_filter_json_from_response,
    parse_sql_from_response,
    parse_steps_from_response,
)
import local_dev  # needed as mock target namespace


# ────────────────────────────────────────────────
# ASYNC CLIENT FIXTURE
# ────────────────────────────────────────────────
@pytest_asyncio.fixture
async def client() -> httpx.AsyncClient:
    """Async ASGI test client — no real network, no DB, no API cost."""
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=web_app),
        base_url="http://testserver",
    ) as ac:
        yield ac


# ────────────────────────────────────────────────
# FILTER JSON FIXTURES
# ────────────────────────────────────────────────
@pytest.fixture
def simple_filter() -> dict:
    """Single criterion, valid field."""
    return {
        "operator": "AND",
        "groups": [
            {
                "operator": "AND",
                "criteria": [
                    {"field": "gmv_30d", "operator": "greater than", "value": 50_000_000}
                ],
            }
        ],
    }


@pytest.fixture
def complex_filter() -> dict:
    """Multi-group AND/OR filter with three criteria."""
    return {
        "operator": "AND",
        "groups": [
            {
                "operator": "AND",
                "criteria": [
                    {"field": "merchant_region",  "operator": "is exactly",   "value": "TP. HCM"},
                    {"field": "gmv_30d",           "operator": "greater than", "value": 50_000_000},
                ],
            },
            {
                "operator": "OR",
                "criteria": [
                    {"field": "app_installed_state", "operator": "is exactly", "value": "Installed"},
                    {"field": "ecopay_active",        "operator": "is exactly", "value": "Yes"},
                ],
            },
        ],
    }


@pytest.fixture
def empty_groups_filter() -> dict:
    """Filter with no groups — should be rejected."""
    return {"operator": "AND", "groups": []}


@pytest.fixture
def unknown_field_filter() -> dict:
    """Filter referencing a field not in CDP_CRITERIA_FIELDS."""
    return {
        "operator": "AND",
        "groups": [{"operator": "AND", "criteria": [
            {"field": "nonexistent_field_xyz", "operator": "equals", "value": 1}
        ]}],
    }


@pytest.fixture
def sql_injection_filter() -> dict:
    """Filter with SQL metacharacters in value — must be blocked."""
    return {
        "operator": "AND",
        "groups": [{"operator": "AND", "criteria": [
            {"field": "merchant_region", "operator": "is exactly",
             "value": "TP. HCM'; DROP TABLE merchants; --"}
        ]}],
    }


@pytest.fixture
def between_filter() -> dict:
    """Between operator with valid [min, max] array."""
    return {
        "operator": "AND",
        "groups": [{"operator": "AND", "criteria": [
            {"field": "average_order_value", "operator": "between", "value": [1_000_000, 5_000_000]}
        ]}],
    }


@pytest.fixture
def duration_filter() -> dict:
    """Duration field with unit."""
    return {
        "operator": "AND",
        "groups": [{"operator": "AND", "criteria": [
            {"field": "purchase_continuity", "operator": "last consecutive",
             "value": 3, "unit": "Months"}
        ]}],
    }


# ────────────────────────────────────────────────
# CLAUDE MOCK RESPONSE FIXTURES
# ────────────────────────────────────────────────
@pytest.fixture
def mock_sql_response() -> str:
    return (
        "```sql\n"
        "-- Generated by QueryMind AI\n"
        "SELECT m.name, SUM(t.amount) AS total_revenue\n"
        "FROM merchants m\n"
        "JOIN transactions t ON t.merchant_id = m.id\n"
        "WHERE t.status = 'completed'\n"
        "GROUP BY m.name\n"
        "ORDER BY total_revenue DESC\n"
        "LIMIT 10\n"
        "```"
    )


@pytest.fixture
def mock_steps_response() -> str:
    return (
        "STEP 1: Lấy dữ liệu từ bảng\n"
        "Câu lệnh SELECT lấy tên merchant và tổng doanh thu.\n\n"
        "STEP 2: Kết nối bảng\n"
        "JOIN kết nối merchants với transactions theo merchant_id.\n\n"
        "STEP 3: Lọc giao dịch\n"
        "WHERE lọc chỉ lấy giao dịch đã hoàn thành.\n\n"
        "STEP 4: Sắp xếp kết quả\n"
        "ORDER BY sắp xếp kết quả từ cao đến thấp.\n"
    )


@pytest.fixture
def mock_filter_json_response() -> str:
    return (
        '{"filters": {"operator": "AND", "groups": [{"operator": "AND", "criteria": ['
        '{"field": "merchant_region", "operator": "is exactly", "value": "TP. HCM"},'
        '{"field": "gmv_30d", "operator": "greater than", "value": 50000000}'
        ']}]}, "confidence": 0.95}'
    )
