"""
Unit tests for build_sql_from_filters(), estimate_audience_sql(),
and simulate_audience_estimate(). No HTTP, no mocks needed — pure Python.

Test IDs: SB-001 through SB-011
"""
import pytest
from conftest import (
    build_sql_from_filters,
    estimate_audience_sql,
    simulate_audience_estimate,
)


class TestBuildSqlFromFilters:

    def test_sb001_simple_numeric_greater_than(self, simple_filter: dict) -> None:
        sql = build_sql_from_filters(simple_filter)
        assert "50000000" in sql
        assert ">" in sql

    def test_sb002_categorical_is_exactly(self) -> None:
        filters = {
            "operator": "AND",
            "groups": [{"operator": "AND", "criteria": [
                {"field": "merchant_region", "operator": "is exactly", "value": "TP. HCM"}
            ]}],
        }
        sql = build_sql_from_filters(filters)
        assert "TP. HCM" in sql

    def test_sb003_between_operator(self, between_filter: dict) -> None:
        sql = build_sql_from_filters(between_filter)
        assert "1000000" in sql
        assert "5000000" in sql
        assert "BETWEEN" in sql.upper()

    def test_sb004_is_one_of_operator(self) -> None:
        filters = {
            "operator": "AND",
            "groups": [{"operator": "AND", "criteria": [
                {"field": "merchant_region", "operator": "is one of",
                 "value": ["TP. HCM", "Ha Noi"]}
            ]}],
        }
        sql = build_sql_from_filters(filters)
        assert "TP. HCM" in sql
        assert "Ha Noi" in sql
        assert "IN" in sql.upper()

    def test_sb005_last_consecutive_operator(self, duration_filter: dict) -> None:
        sql = build_sql_from_filters(duration_filter)
        assert "3" in sql
        assert "consecutive" in sql.lower()

    def test_sb006_multi_group_and_or(self, complex_filter: dict) -> None:
        sql = build_sql_from_filters(complex_filter)
        assert sql
        assert "AND" in sql.upper()
        assert "OR" in sql.upper()

    def test_sb007_unknown_field_raises(self, unknown_field_filter: dict) -> None:
        with pytest.raises((ValueError, KeyError)):
            build_sql_from_filters(unknown_field_filter)

    def test_sb008_sql_injection_in_string_raises(self, sql_injection_filter: dict) -> None:
        with pytest.raises(ValueError, match="disallowed"):
            build_sql_from_filters(sql_injection_filter)

    def test_sb009_empty_groups_returns_fallback(self) -> None:
        f = {"operator": "AND", "groups": []}
        sql = build_sql_from_filters(f)
        assert sql == "1=1"

    def test_sb010_is_not_operator(self) -> None:
        filters = {
            "operator": "AND",
            "groups": [{"operator": "AND", "criteria": [
                {"field": "app_installed_state", "operator": "is not", "value": "Installed"}
            ]}],
        }
        sql = build_sql_from_filters(filters)
        assert "!=" in sql or "<>" in sql


class TestEstimateAudienceSql:

    def test_sb011_output_starts_with_comment(self, simple_filter: dict) -> None:
        sql = estimate_audience_sql(simple_filter)
        assert sql.startswith("-- Generated by QueryMind AI CDP")

    def test_sb012_output_contains_count_distinct(self, simple_filter: dict) -> None:
        sql = estimate_audience_sql(simple_filter)
        assert "COUNT(DISTINCT m.id)" in sql

    def test_sb013_output_is_nonempty_string(self, simple_filter: dict) -> None:
        result = estimate_audience_sql(simple_filter)
        assert isinstance(result, str) and len(result) > 0

    def test_sb014_output_embeds_where_clause(self, simple_filter: dict) -> None:
        where = build_sql_from_filters(simple_filter)
        sql = estimate_audience_sql(simple_filter)
        assert where in sql


class TestSimulateAudienceEstimate:

    def test_sb015_required_keys_present(self, simple_filter: dict) -> None:
        result = simulate_audience_estimate(simple_filter)
        required = {"audience_size", "total_merchants", "coverage_pct",
                    "reach_reliability", "forecasted_conversion", "delta_pct"}
        assert required.issubset(result.keys())

    def test_sb016_audience_size_within_bounds(self, simple_filter: dict) -> None:
        result = simulate_audience_estimate(simple_filter)
        assert 500 <= result["audience_size"] <= 95_000

    def test_sb017_total_merchants_is_100k(self, simple_filter: dict) -> None:
        assert simulate_audience_estimate(simple_filter)["total_merchants"] == 100_000

    def test_sb018_coverage_pct_between_0_and_100(self, simple_filter: dict) -> None:
        pct = simulate_audience_estimate(simple_filter)["coverage_pct"]
        assert 0.0 <= pct <= 100.0

    def test_sb019_more_criteria_produces_smaller_audience(
        self, complex_filter: dict, simple_filter: dict
    ) -> None:
        simple_est  = simulate_audience_estimate(simple_filter)
        complex_est = simulate_audience_estimate(complex_filter)
        assert complex_est["audience_size"] <= simple_est["audience_size"]

    def test_sb020_audience_floor_enforced(self) -> None:
        """20 criteria should still respect the 500-merchant floor."""
        heavy_filter = {
            "operator": "AND",
            "groups": [{"operator": "AND", "criteria": [
                {"field": "gmv_30d", "operator": "greater than", "value": 50_000_000}
            ] * 20}],
        }
        result = simulate_audience_estimate(heavy_filter)
        assert result["audience_size"] >= 500
